import { AnimatedGroup } from '@/components/ui/animated-group'

export function Terms() {
    return (
        <div className="mx-auto max-w-4xl px-6 py-20">
            <AnimatedGroup>
                <div className="glass-panel rounded-[2rem] p-10 md:p-16 border border-white/60">
                    <h1 className="font-heading text-4xl text-foreground mb-8">Terms of Service</h1>
                    <p className="text-sm text-muted-foreground mb-8">Last Updated: May 2026</p>
                    
                    <div className="space-y-6 text-muted-foreground leading-relaxed">
                        <p>
                            Welcome to Vesta. By accessing or using our Yield Prediction platform, you agree to be bound by these dummy Terms of Service.
                        </p>
                        <h3 className="font-heading text-xl text-foreground mt-8 mb-4">1. Use of the Service</h3>
                        <p>
                            You may use our platform solely for informational and predictive purposes. The predictions generated by our Machine Learning models are estimates based on historical data and should not be taken as absolute guarantees of agricultural output.
                        </p>
                        <h3 className="font-heading text-xl text-foreground mt-8 mb-4">2. Liability</h3>
                        <p>
                            Vesta, its creators (antiperfect), and affiliates shall not be held liable for any agricultural losses, financial damages, or resource misallocations resulting from the use of our predictive models. Always consult with certified agronomists for critical farming decisions.
                        </p>
                        <h3 className="font-heading text-xl text-foreground mt-8 mb-4">3. Intellectual Property</h3>
                        <p>
                            The Vesta platform, including its original design (Pinterest chic aesthetic), frontend architecture, and predictive models, are the intellectual property of its creators. You may not reproduce or duplicate the source code without permission.
                        </p>
                        <h3 className="font-heading text-xl text-foreground mt-8 mb-4">4. Modifications</h3>
                        <p>
                            We reserve the right to modify or replace these Terms at any time. Your continued use of the platform after any changes constitutes acceptance of the new Terms.
                        </p>
                    </div>
                </div>
            </AnimatedGroup>
        </div>
    )
}
